"""
Turn an existing saved transcript.txt (from run_pipeline.py or any of the
run_*_eval_openai.py scripts) into real spoken audio via OpenAI's TTS API - one
audio file per turn, named so playing them in order reconstructs the conversation.

This is a post-processing step, not a live relay: the conversation text already
exists (generated by the existing, working text pipeline) - this script only adds
"you can hear it" on top, one plain REST call per turn. No dialogue is written here.

Setup:
    pip install openai --break-system-packages
    export OPENAI_API_KEY=your_key_here

Usage:
    python generate_audio.py path/to/transcript.txt
    python generate_audio.py path/to/transcript.txt --output-dir path/to/audio_out
    python generate_audio.py path/to/transcript.txt --model tts-1-hd
    python generate_audio.py path/to/transcript.txt --voice-map ESTIMATOR:onyx,CUSTOMER:nova
"""

import argparse
import json
import re
import sys
from pathlib import Path

try:
    from openai import OpenAI
except ImportError:
    sys.exit("Missing dependency. Install with:\n    pip install openai --break-system-packages")

# Base role -> voice. Matches the role labels actually used across the codebase's
# saved transcripts: "ESTIMATOR:"/"CUSTOMER:" (estimator stage), "CALLER:"/
# "COUNTERPARTY (name):" (caller stage), "CLOSER:"/"COUNTERPARTY (name):" (closer stage).
DEFAULT_VOICE_MAP = {
    "ESTIMATOR": "onyx",
    "CALLER": "onyx",
    "CLOSER": "onyx",
    "CUSTOMER": "nova",
    "COUNTERPARTY": "nova",
}
DEFAULT_MODEL = "tts-1"
FALLBACK_VOICE = "alloy"

# Matches a turn's leading role label, e.g. "ESTIMATOR: ", "COUNTERPARTY (Tough
# negotiator): " - captures the base role name (group 1) separately from any
# parenthetical persona label, since voice selection is per base role.
TURN_RE = re.compile(r'^([A-Z][A-Z ]*?)(?:\s*\([^)]*\))?:\s?', re.MULTILINE)


def parse_transcript(text: str) -> list[dict]:
    """Split a saved transcript into turns. Each turn's spoken text runs until the
    next role label, so multi-line turns are handled correctly."""
    matches = list(TURN_RE.finditer(text))
    if not matches:
        raise ValueError("No 'ROLE: ...' turns found in this transcript.")

    turns = []
    for i, m in enumerate(matches):
        role = m.group(1).strip()
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        turns.append({"role": role, "text": text[start:end].strip()})
    return turns


def parse_voice_map(arg: str | None) -> dict:
    voice_map = dict(DEFAULT_VOICE_MAP)
    if arg:
        for pair in arg.split(","):
            role, _, voice = pair.partition(":")
            if role and voice:
                voice_map[role.strip().upper()] = voice.strip()
    return voice_map


def generate_audio(client: OpenAI, transcript_path: str, output_dir: str | None = None,
                    model: str = DEFAULT_MODEL, voice_map: dict | None = None) -> Path:
    voice_map = voice_map or DEFAULT_VOICE_MAP
    turns = parse_transcript(Path(transcript_path).read_text())

    out_dir = Path(output_dir or (Path(transcript_path).parent / "audio"))
    out_dir.mkdir(parents=True, exist_ok=True)

    manifest = []
    for i, turn in enumerate(turns, start=1):
        if not turn["text"]:
            continue
        voice = voice_map.get(turn["role"], FALLBACK_VOICE)
        response = client.audio.speech.create(model=model, voice=voice, input=turn["text"])
        filename = f"turn_{i:02d}_{turn['role']}.mp3"
        (out_dir / filename).write_bytes(response.read())
        print(f"[{i:02d}] {turn['role']} ({voice}) -> {filename}")
        manifest.append({"turn": i, "role": turn["role"], "text": turn["text"], "audio_file": filename})

    (out_dir / "audio_manifest.json").write_text(json.dumps(manifest, indent=2))
    return out_dir


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("transcript_path")
    parser.add_argument("--output-dir", default=None)
    parser.add_argument("--model", default=DEFAULT_MODEL, choices=["tts-1", "tts-1-hd", "gpt-4o-mini-tts"])
    parser.add_argument("--voice-map", default=None,
                         help="Comma-separated ROLE:voice overrides, e.g. ESTIMATOR:onyx,CUSTOMER:nova")
    args = parser.parse_args()

    client = OpenAI()  # reads OPENAI_API_KEY from env
    voice_map = parse_voice_map(args.voice_map)
    out_dir = generate_audio(client, args.transcript_path, args.output_dir, args.model, voice_map)
    print(f"\nSaved {len(list(out_dir.glob('turn_*.mp3')))} audio files to {out_dir}/")


if __name__ == "__main__":
    main()
